# Generated by Django 4.2.1 on 2023-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.IntegerField(verbose_name='Отправитель')),
                ('to_user', models.IntegerField(verbose_name='Получатель')),
            ],
        ),
        migrations.CreateModel(
            name='FriendWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
            ],
        ),
    ]
